import { pickAutoAnswer } from './phrases'
import type {
  PhraseCard,
  RoundRevealResult,
  RoundState,
  TranslatorAnswer,
  TranslatorPlayer,
} from './types'

const POINTS_PER_VOTE = 100
const MAJORITY_BONUS = 50

export function createPlayer(name: string): TranslatorPlayer {
  return {
    id: `p-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    name,
    score: 0,
  }
}

export function initRound(roundIndex: number, phrase: PhraseCard): RoundState {
  return {
    roundIndex,
    phrase,
    answers: [],
    answerTurnIndex: 0,
    votingTurnIndex: 0,
    shuffledAnswerIds: [],
    revealResults: [],
  }
}

export function getCurrentAnswerPlayerId(
  round: RoundState,
  players: TranslatorPlayer[]
): string | null {
  return players[round.answerTurnIndex]?.id ?? null
}

export function getCurrentVotingPlayerId(
  round: RoundState,
  players: TranslatorPlayer[]
): string | null {
  return players[round.votingTurnIndex]?.id ?? null
}

function createAnswer(playerId: string, text: string, isAutoGenerated: boolean): TranslatorAnswer {
  return {
    id: `a-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    playerId,
    text,
    isAutoGenerated,
    votes: [],
  }
}

export function submitAnswer(
  round: RoundState,
  playerId: string,
  players: TranslatorPlayer[],
  text: string
): RoundState | null {
  const trimmed = text.trim()
  if (!trimmed) return null
  const expectedId = getCurrentAnswerPlayerId(round, players)
  if (!expectedId || expectedId !== playerId) return null

  const answer = createAnswer(playerId, trimmed, false)
  const answers = [...round.answers, answer]
  const answerTurnIndex = round.answerTurnIndex + 1

  return { ...round, answers, answerTurnIndex }
}

/** Игрок сказал ответ вслух — ход переходит дальше без записи в голосование. */
export function advanceSpokenAnswerTurn(
  round: RoundState,
  playerId: string,
  players: TranslatorPlayer[]
): RoundState | null {
  const expectedId = getCurrentAnswerPlayerId(round, players)
  if (!expectedId || expectedId !== playerId) return null
  return { ...round, answerTurnIndex: round.answerTurnIndex + 1 }
}

export function skipAnswer(
  round: RoundState,
  playerId: string,
  players: TranslatorPlayer[]
): RoundState | null {
  const expectedId = getCurrentAnswerPlayerId(round, players)
  if (!expectedId || expectedId !== playerId) return null

  const answer = createAnswer(playerId, pickAutoAnswer(), true)
  const answers = [...round.answers, answer]
  const answerTurnIndex = round.answerTurnIndex + 1
  return { ...round, answers, answerTurnIndex }
}

export function startVotingPhase(round: RoundState): RoundState {
  const shuffledAnswerIds = shuffleIds(round.answers.map((a) => a.id))
  return {
    ...round,
    shuffledAnswerIds,
    votingTurnIndex: 0,
  }
}

function shuffleIds(ids: string[]): string[] {
  const arr = [...ids]
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}

export function getAnswerById(round: RoundState, answerId: string): TranslatorAnswer | undefined {
  return round.answers.find((a) => a.id === answerId)
}

export function isOwnAnswer(round: RoundState, voterId: string, answerId: string): boolean {
  const answer = getAnswerById(round, answerId)
  return answer?.playerId === voterId
}

export function getVotableAnswers(round: RoundState, voterId: string): TranslatorAnswer[] {
  return round.answers.filter((a) => a.playerId !== voterId)
}

export function canVote(round: RoundState, voterId: string): boolean {
  return getVotableAnswers(round, voterId).length > 0
}

export function submitVote(
  round: RoundState,
  voterId: string,
  players: TranslatorPlayer[],
  answerId: string
): RoundState | null {
  const expectedId = getCurrentVotingPlayerId(round, players)
  if (!expectedId || expectedId !== voterId) return null
  if (isOwnAnswer(round, voterId, answerId)) return null
  const answer = getAnswerById(round, answerId)
  if (!answer || answer.votes.includes(voterId)) return null

  const answers = round.answers.map((a) =>
    a.id === answerId ? { ...a, votes: [...a.votes, voterId] } : a
  )
  const votingTurnIndex = round.votingTurnIndex + 1

  return { ...round, answers, votingTurnIndex }
}

export function hasMajorityBonus(voteCount: number, playerCount: number): boolean {
  return voteCount > playerCount * 0.5
}

export function computeRoundResults(
  round: RoundState,
  playerCount: number
): RoundRevealResult[] {
  return round.answers.map((answer) => {
    const voteCount = answer.votes.length
    const hasBonus = hasMajorityBonus(voteCount, playerCount)
    const pointsEarned = voteCount * POINTS_PER_VOTE + (hasBonus ? MAJORITY_BONUS : 0)
    return {
      answerId: answer.id,
      playerId: answer.playerId,
      text: answer.text,
      isAutoGenerated: answer.isAutoGenerated,
      voteCount,
      pointsEarned,
      hasMajorityBonus: hasBonus,
    }
  })
}

export function applyRoundScores(
  players: TranslatorPlayer[],
  results: RoundRevealResult[]
): TranslatorPlayer[] {
  const pointsByPlayer = new Map<string, number>()
  for (const r of results) {
    pointsByPlayer.set(r.playerId, (pointsByPlayer.get(r.playerId) ?? 0) + r.pointsEarned)
  }
  return players.map((p) => ({
    ...p,
    score: p.score + (pointsByPlayer.get(p.id) ?? 0),
  }))
}

export function accumulateVotesReceived(
  current: Record<string, number>,
  results: RoundRevealResult[]
): Record<string, number> {
  const next = { ...current }
  for (const r of results) {
    next[r.playerId] = (next[r.playerId] ?? 0) + r.voteCount
  }
  return next
}

export function incrementAutoAnswerCount(
  current: Record<string, number>,
  playerId: string
): Record<string, number> {
  return { ...current, [playerId]: (current[playerId] ?? 0) + 1 }
}

export function getLeaderboard(players: TranslatorPlayer[]): TranslatorPlayer[] {
  return [...players].sort((a, b) => b.score - a.score)
}

export type FinalStats = {
  winner: TranslatorPlayer | null
  ranking: TranslatorPlayer[]
  mostVoted: TranslatorPlayer | null
  mostAutoAnswers: TranslatorPlayer | null
}

export function computeFinalStats(
  players: TranslatorPlayer[],
  totalVotesReceived: Record<string, number>,
  autoAnswerCounts: Record<string, number>
): FinalStats {
  const ranking = getLeaderboard(players)
  const winner = ranking[0] ?? null

  const byVotes = [...players].sort(
    (a, b) => (totalVotesReceived[b.id] ?? 0) - (totalVotesReceived[a.id] ?? 0)
  )
  const mostVoted = byVotes[0] && (totalVotesReceived[byVotes[0].id] ?? 0) > 0 ? byVotes[0] : null

  const byAuto = [...players].sort(
    (a, b) => (autoAnswerCounts[b.id] ?? 0) - (autoAnswerCounts[a.id] ?? 0)
  )
  const mostAutoAnswers =
    byAuto[0] && (autoAnswerCounts[byAuto[0].id] ?? 0) > 0 ? byAuto[0] : null

  return { winner, ranking, mostVoted, mostAutoAnswers }
}

export { POINTS_PER_VOTE, MAJORITY_BONUS }
