export const ROUND_COUNT_OPTIONS = [5, 7, 10] as const
export type RoundCountOption = (typeof ROUND_COUNT_OPTIONS)[number]

export const MIN_PLAYERS = 3

export type PhraseCategory =
  | 'drunk'
  | 'female_subtext'
  | 'male_logic'
  | 'corporate'
  | 'parents_chat'
  | 'exes_and_chats'
  | 'delivery_marketplaces'
  | 'family_chat'
  | 'dating'
  | 'friends_party'

export type PhraseCard = {
  id: string
  category: PhraseCategory
  categoryLabel: string
  text: string
  hint: string
}

export type TranslatorPlayer = {
  id: string
  name: string
  score: number
}

export type TranslatorAnswer = {
  id: string
  playerId: string
  text: string
  isAutoGenerated: boolean
  votes: string[]
}

export type TranslatorPhase =
  | 'setup'
  | 'answers'
  | 'voting'
  | 'reveal'
  | 'final'

export type RoundRevealResult = {
  answerId: string
  playerId: string
  text: string
  isAutoGenerated: boolean
  voteCount: number
  pointsEarned: number
  hasMajorityBonus: boolean
}

export type RoundState = {
  roundIndex: number
  phrase: PhraseCard
  answers: TranslatorAnswer[]
  answerTurnIndex: number
  votingTurnIndex: number
  shuffledAnswerIds: string[]
  revealResults: RoundRevealResult[]
}

/** Состояние партии — отделено от UI для будущего онлайн-режима */
export type TranslatorGameState = {
  phase: TranslatorPhase
  roundCount: RoundCountOption
  players: TranslatorPlayer[]
  phrases: PhraseCard[]
  round: RoundState | null
  autoAnswerCounts: Record<string, number>
  totalVotesReceived: Record<string, number>
}

export const MICRO_HINTS = [
  'Переведи это на нормальный язык.',
  'Смешно, жизненно или подозрительно точно.',
  'За свой ответ голосовать нельзя. Мы все видим.',
  'Сейчас узнаем, кто тут главный эксперт по намекам.',
  'Ответы анонимные. Пока что.',
  'Раунд раскрыт. Держитесь.',
] as const
